- name: Configure homelab servers
  hosts: homelab
  become: yes
  roles:
    - role: install_basic_apps
    - role: authorized_keys
      vars:
        add_authorized_keys:
          - "{{ lookup('file', './files/gabriel_key.pub') }}"
    - role: configure_sudo_nopasswd
  