- name: Configure homelab servers
  hosts: homelab
  become: yes
  roles:
    - role: common
    - role: authorized_keys
      vars:
        add_authorized_keys:
          - "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    - role: configure_sudo_nopasswd
  