galaxy_info:
  role_name: add_authorized_keys
  description: Add authorized keys to remote user
  author: Myro Stadler
  license: GPL-3.0-only
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - bionic
