- name: Update and upgrade packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install basic utilities
  apt:
    name:
      - vim
      - curl
      - git
      - unzip
      - net-tools
      - qemu-guest-agent
      - prometheus-node-exporter
    state: present

- name: Ensure essential services are running and enabled
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - ssh
    - qemu-guest-agent
    - prometheus-node-exporter
  when:
    - ansible_virtualization_type != "lxc" or item != "qemu-guest-agent"