- name: Update and upgrade packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install basic utilities
  apt:
    name:
      - vim
      - curl
      - git
      - unzip
      - net-tools
      - qemu-guest-agent
    state: present
