all:
  hosts:
    pve:
      ansible_host: 192.168.2.63
  children:
    demos:
      hosts:
        demo1:
          ansible_host: 192.168.2.76
        demo2:
          ansible_host: 192.168.2.25
    homelab:
      hosts:
        localhost:
          ansible_connection: local
        dockerhost:
          ansible_host: 192.168.2.66
        vault:
          ansible_host: 192.168.2.75
        tailscale:
          ansible_host: 192.168.2.69
        pihole:
          ansible_host: 192.168.2.31

          

