all:
  hosts:
    pve:
      ansible_host: 192.168.2.63
    dockerhost:
      ansible_host: 192.168.2.66
    vault:
      ansible_host: 192.168.2.75
    tailscale:
      ansible_host: 192.168.2.135
    pihole:
      ansible_host: 192.168.2.31
    automator:
      ansible_connection: local

  children:
    homelab:
      hosts:
        dockerhost:
        vault:
        tailscale:
        pihole:
        automator:

    vms:
      hosts:
        dockerhost:
        tailscale:

    lxcs:
      hosts:
        vault:
        pihole:
