---
- name: Get the remote user
  command: whoami
  register: remote_user
  become: false
  changed_when: false
- name: Ensure correct permissions on authorized_keys
  file:
    dest: "/home/{{ remote_user.stdout }}/.ssh/authorized_keys"
    state: file
    mode: 0600
- name: Add keys to authorized_keys
  lineinfile:
    dest: "/home/{{ remote_user.stdout }}/.ssh/authorized_keys"
    line: "{{ item }}"
  with_items: "{{ add_authorized_keys }}"
